Resources:
  rdsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 'sls-hello-world-secret'
      GenerateSecretString:
        ExcludePunctuation: true
        IncludeSpace: false
        RequireEachIncludedType: true
        PasswordLength: 25
        GenerateStringKey: 'password'
        SecretStringTemplate: '{"username": "slsAdmin"}'

  rdsInstance:
    DependsOn: slsVpcGatewayAttachment
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: ${self:custom.DB_NAME}
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref rdsSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref rdsSecret, ':SecretString:password}}' ]]
      Engine: mysql
      EngineVersion: 5.7
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      PubliclyAccessible: false
      BackupRetentionPeriod: 0
      DBSubnetGroupName: !Ref rdsSubnetGroup
      VPCSecurityGroups:
        - !GetAtt rdsSecurityGroup.GroupId

  rdsSecretInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
        SecretId: !Ref rdsSecret
        TargetId: !Ref rdsInstance
        TargetType: AWS::RDS::DBInstance

  rdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "sls RDS subnet group"
      SubnetIds:
        - !Ref subnetA
        - !Ref subnetC
      Tags:
        - Key: "Name"
          Value: "sls-rds-subnet-group"